#!/usr/bin/env sh

TARGET_DIR=".githooks"

prev_head="$1"
new_head="$2"
checkout_type="$3" # 1 = branch checkout, 0 = file checkout

# Only run on branch checkout
if [ "$checkout_type" = "1" ]; then
  # Prevent crashing on first checkout (orphan branches)
  if [ -z "$prev_head" ] || [ -z "$new_head" ]; then
    exit 0
  fi

  if git diff --name-only "$prev_head" "$new_head" | grep -q "^$TARGET_DIR/"; then
    echo "---------------------------------------------------------------------------------"
    echo "WARNING: The branch you switched to has different hooks the previous branch."
    echo "    Review the changes in $TARGET_DIR/ and adopt the new hooks as needed."
    echo "---------------------------------------------------------------------------------"
  fi
fi

exit 0
