#!/usr/bin/env sh

HOOK_TYPE=$(basename "$0")
HOOK_DIR="$(dirname "$0")/${HOOK_TYPE}.d"

if [ -d "$HOOK_DIR" ]; then
  for script in "$HOOK_DIR"/*; do
    # Check if it is a file and is executable
    if [ -f "$script" ] && [ -x "$script" ]; then
      echo "Running $HOOK_TYPE hook: $(basename "$script")"

      if ! "$script" "$@"; then
        echo "Error: Hook script '$(basename "$script")' failed."
        exit 1
      fi
    fi
  done
fi
